FROM eclipse-temurin:17-jdk-alpine as builder

WORKDIR /app
COPY . .
RUN sh ./gradlew -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 clean bootJar
RUN cp build/libs/PathDiscoverer-*.jar app.jar


FROM eclipse-temurin:17-jdk-alpine

ENV POSTGRES_DB_NAME=log
VOLUME /tmp
WORKDIR /app
COPY --from=builder /app/app.jar /app/app.jar
COPY --from=builder /app/podman/entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
